title: Van
author:
  name: Van
  email: van@test.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Digital playground for Van Lang Pham'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
