title: 'Van Lang Pham'
default_lang: en
author:
  name: 'Van Lang Pham'
  email: vanlang.pham@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Digital playground for Van Lang Pham'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
